### ISSUE TITLE
Discord Releases.

### ISSUE THREAD

**Issue by DrNoSleep** [MattOverthrow/PSGrabber#2]
Please keep in mind there are many different releases of discord.
Here are the current releases of the different official discord clients.
Discord
DiscordPTB
DiscordCanary
DiscordDevelopment

Your code seems to only work with stable and canary atm.

**Comment by DrNoSleep** [comment]
my bad, you seem to have support for all stable ptb and canary
I still think Development would be a good add though as I and a few friends use it. to avoid things like this.

**Comment by MattOverthrow** [comment]
Fixed but as it takes longer to scan for these tokens in different locations I commented it out - feel free to uncomment.
